name: Super-Linter

on: push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: .
          VALIDATE_ALL_CODEBASE: false  
          AUTO_FIX: true 

  build:
       runs-on: ubuntu-latest
       steps:
        - uses: actions/checkout@v4
        - name: Setup .NET
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: 8.0.x
        - name: Restore dependencies
          run: dotnet restore WeatherDashboard/
        - name: Build
          run: dotnet build WeatherDashboard/ --no-restore
        - name: Test
          run: dotnet test WeatherDashboard/ --no-build --verbosity normal


    
