name: Super-Linter

on: push

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: .
          VALIDATE_ALL_CODEBASE: false  
          AUTO_FIX: true 

  build:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # .NET Build
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x' # Adjust version as needed

      - name: Restore .NET dependencies
        run: dotnet restore

      - name: Build .NET project
        run: dotnet build --no-restore --configuration Release

      # Angular Build
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Adjust as needed

      - name: Install Angular dependencies
        run: npm install
        working-directory: frontend # Adjust if Angular project is in a different folder

      - name: Build Angular project
        run: npm run build --if-present
        working-directory: frontend

  test:
    name: Test Project
    runs-on: ubuntu-latest
    needs: build  # Ensures tests run only if build is successful
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # .NET Tests
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x' # Adjust version as needed

      - name: Restore .NET dependencies
        run: dotnet restore

      - name: Run .NET tests
        run: dotnet test --no-build --verbosity normal

      # Angular Tests
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Adjust as needed

      - name: Install Angular dependencies
        run: npm install
        working-directory: frontend # Adjust if Angular project is in a different folder

      - name: Run Angular tests
        run: npm test -- --watch=false --browsers=ChromeHeadless
        working-directory: frontend
