name: Super-Linter

on: push

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: .
          VALIDATE_ALL_CODEBASE: false  
          AUTO_FIX: true 

  build:
    name: Build .NET Backend and Angular Frontend
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0'

      - name: Restore .NET dependencies
        run: dotnet restore

      - name: Build .NET Application
        run: dotnet build --configuration Release

      - name: Set up Node.js (Angular)
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Angular dependencies
        run: npm install

      - name: Build Angular Application
        run: npm run build --prod

  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: build  # Runs after build job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up .NET
        uses: actions/setup-dotnet@v2
      - name: Run .NET Tests
        run: dotnet test

      - name: Set up Node.js (Angular)
        uses: actions/setup-node@v2
      - name: Run Angular Tests
        run: npm run test -- --watch=false --browsers=ChromeHeadless
